### ISSUE TITLE
wxc-tab-bar 底部icon图标不显示

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#99]
![qq 20171222102327](https://user-images.githubusercontent.com/10809790/34282691-68bd6b28-e702-11e7-9d08-afa5f693d6ae.png)

**Comment by tw93** [comment]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- 
- 

#### Expected behavior and actual behavior.
- 
- 

#### Steps to reproduce the problem.
- 
- 

请按照这个格式提issue
